from future import annotations

import copy
import hashlib
import json
from collections import defaultdict
from typing import Any

class StoryValidationError(ValueError):
"""Raised when generated story content is unsafe or structurally invalid."""

class StoryValidator:
"""
Strict validator for AI-generated WHAT HAPPENS? story content.

The validator sits between StoryGenerator and GameEngine:

    Gemini
      ↓
    StoryValidator
      ↓
    validated story
      ↓
    GameEngine

This class contains NO gameplay execution and NEVER calls Gemini.

Its purpose is to guarantee that the story supplied to the deterministic
engine has valid identifiers, references, timers, branching, endings,
roles, conditions, effects, and player-count compatibility.
"""

MIN_TIMER_SECONDS = 10
MAX_TIMER_SECONDS = 3600

MIN_TITLE_LENGTH = 1
MAX_TITLE_LENGTH = 200

MIN_TEXT_LENGTH = 1
MAX_TEXT_LENGTH = 4000

MIN_ROLES = 1
MAX_ROLES = 50

MIN_SCENES = 1
MAX_SCENES = 200

MIN_CHOICES_PER_SCENE = 1
MAX_CHOICES_PER_SCENE = 50

ALLOWED_CONDITION_TYPES = {
    "flag",
    "variable",
    "knowledge",
    "relationship",
}

ALLOWED_OPERATORS = {
    "eq",
    "ne",
    "gt",
    "gte",
    "lt",
    "lte",
    "contains",
}

ALLOWED_EFFECT_KEYS = {
    "set_flags",
    "remove_flags",
    "set_variables",
    "add_variables",
    "relationships",
    "knowledge",
    "secrets",
    "character_state",
    "text",
    "description",
}

@classmethod
def validate(
    cls,
    story: dict[str, Any],
    player_count: int | None = None,
) -> dict[str, Any]:
    """
    Validate a story and return a defensive deep copy.

    The returned object is safe for the next layer to consume.

    Args:
        story:
            Candidate story JSON generated by Gemini.

        player_count:
            Number of human players expected to participate.

            If supplied, the validator guarantees that enough playable
            roles exist.

    Raises:
        StoryValidationError:
            If any structural or semantic validation fails.
    """

    if not isinstance(story, dict):
        cls.fail("Story must be a JSON object.")

    normalized = copy.deepcopy(story)

    cls._validate_top_level(normalized)
    roles = cls._validate_roles(normalized)
    scenes = cls._validate_scenes(normalized)

    role_ids = set(roles)
    scene_ids = set(scenes)

    cls._validate_first_scene(
        normalized,
        scene_ids,
    )

    cls._validate_scene_references(
        scenes,
        role_ids,
        scene_ids,
    )

    cls._validate_cross_references(
        normalized,
        roles,
        scenes,
    )

    cls._validate_story_graph(
        normalized,
        scenes,
    )

    cls._validate_player_count(
        roles,
        player_count,
    )

    return normalized

# ============================================================
# TOP LEVEL
# ============================================================

@classmethod
def _validate_top_level(
    cls,
    story: dict[str, Any],
) -> None:

    required_fields = {
        "title",
        "roles",
        "scenes",
    }

    missing = sorted(
        field
        for field in required_fields
        if field not in story
    )

    if missing:
        cls.fail(
            "Story is missing required fields: "
            + ", ".join(missing)
        )

    title = story.get("title")

    if not isinstance(title, str):
        cls.fail("Story title must be a string.")

    title = title.strip()

    if not title:
        cls.fail("Story title cannot be empty.")

    if len(title) > cls.MAX_TITLE_LENGTH:
        cls.fail(
            f"Story title exceeds {cls.MAX_TITLE_LENGTH} characters."
        )

    roles = story.get("roles")

    if not isinstance(roles, list):
        cls.fail("Story roles must be a list.")

    if not roles:
        cls.fail("Story must contain at least one role.")

    if len(roles) > cls.MAX_ROLES:
        cls.fail(
            f"Story contains too many roles: {len(roles)}."
        )

    scenes = story.get("scenes")

    if not isinstance(scenes, list):
        cls.fail("Story scenes must be a list.")

    if not scenes:
        cls.fail("Story must contain at least one scene.")

    if len(scenes) > cls.MAX_SCENES:
        cls.fail(
            f"Story contains too many scenes: {len(scenes)}."
        )

    first_scene_id = story.get("first_scene_id")

    if first_scene_id is not None and not isinstance(
        first_scene_id,
        str,
    ):
        cls.fail("first_scene_id must be a string.")

# ============================================================
# ROLES
# ============================================================

@classmethod
def _validate_roles(
    cls,
    story: dict[str, Any],
) -> dict[str, dict[str, Any]]:

    roles = story["roles"]

    result: dict[str, dict[str, Any]] = {}
    role_names: set[str] = set()

    for index, role in enumerate(roles):

        path = f"roles[{index}]"

        if not isinstance(role, dict):
            cls.fail(f"{path} must be an object.")

        role_id = role.get("id")

        cls._require_id(
            role_id,
            f"{path}.id",
        )

        if role_id in result:
            cls.fail(
                f"Duplicate role id: {role_id}"
            )

        name = role.get("name")

        if not isinstance(name, str) or not name.strip():
            cls.fail(
                f"{path}.name must be a non-empty string."
            )

        normalized_name = name.strip().casefold()

        if normalized_name in role_names:
            cls.fail(
                f"Duplicate role name: {name}"
            )

        role_names.add(normalized_name)

        secret_description = role.get(
            "secret_description"
        )

        if not isinstance(
            secret_description,
            str,
        ) or not secret_description.strip():
            cls.fail(
                f"{path}.secret_description must be a non-empty string."
            )

        playable = role.get(
            "playable",
            True,
        )

        if not isinstance(playable, bool):
            cls.fail(
                f"{path}.playable must be boolean."
            )

        result[role_id] = role

    if not any(
        bool(role.get("playable", True))
        for role in result.values()
    ):
        cls.fail(
            "Story must contain at least one playable role."
        )

    return result

# ============================================================
# SCENES
# ============================================================

@classmethod
def _validate_scenes(
    cls,
    story: dict[str, Any],
) -> dict[str, dict[str, Any]]:

    scenes = story["scenes"]

    result: dict[str, dict[str, Any]] = {}

    for index, scene in enumerate(scenes):

        path = f"scenes[{index}]"

        if not isinstance(scene, dict):
            cls.fail(f"{path} must be an object.")

        scene_id = scene.get("id")

        cls._require_id(
            scene_id,
            f"{path}.id",
        )

        if scene_id in result:
            cls.fail(
                f"Duplicate scene id: {scene_id}"
            )

        public_text = scene.get("public_text")

        if not isinstance(
            public_text,
            str,
        ) or not public_text.strip():
            cls.fail(
                f"{path}.public_text must be a non-empty string."
            )

        if len(public_text) > cls.MAX_TEXT_LENGTH:
            cls.fail(
                f"{path}.public_text is too long."
            )

        timer_seconds = scene.get(
            "timer_seconds"
        )

        if not isinstance(
            timer_seconds,
            int,
        ) or isinstance(
            timer_seconds,
            bool,
        ):
            cls.fail(
                f"{path}.timer_seconds must be an integer."
            )

        if not (
            cls.MIN_TIMER_SECONDS
            <= timer_seconds
            <= cls.MAX_TIMER_SECONDS
        ):
            cls.fail(
                f"{path}.timer_seconds must be between "
                f"{cls.MIN_TIMER_SECONDS} and "
                f"{cls.MAX_TIMER_SECONDS}."
            )

        choices = scene.get("choices")

        if not isinstance(choices, list):
            cls.fail(
                f"{path}.choices must be a list."
            )

        if len(choices) < cls.MIN_CHOICES_PER_SCENE:
            cls.fail(
                f"{path} must contain at least one choice."
            )

        if len(choices) > cls.MAX_CHOICES_PER_SCENE:
            cls.fail(
                f"{path} contains too many choices."
            )

        eligible_roles = scene.get(
            "eligible_roles",
            [],
        )

        if not isinstance(
            eligible_roles,
            list,
        ):
            cls.fail(
                f"{path}.eligible_roles must be a list."
            )

        if len(eligible_roles) != len(
            set(eligible_roles)
        ):
            cls.fail(
                f"{path}.eligible_roles contains duplicate role ids."
            )

        for role_id in eligible_roles:
            cls._require_id(
                role_id,
                f"{path}.eligible_roles",
            )

        ending = scene.get("ending")

        if ending is not None:
            cls._validate_ending(
                ending,
                path,
            )

        transitions = scene.get(
            "transitions",
            [],
        )

        if not isinstance(
            transitions,
            list,
        ):
            cls.fail(
                f"{path}.transitions must be a list."
            )

        late_join = scene.get(
            "late_join",
            {},
        )

        if not isinstance(
            late_join,
            dict,
        ):
            cls.fail(
                f"{path}.late_join must be an object."
            )

        result[scene_id] = scene

    return result

# ============================================================
# FIRST SCENE
# ============================================================

@classmethod
def _validate_first_scene(
    cls,
    story: dict[str, Any],
    scene_ids: set[str],
) -> None:

    first_scene_id = story.get(
        "first_scene_id"
    )

    if first_scene_id is None:
        # Compatibility with the engine's historical behaviour:
        # the first scene in the list is the first scene.
        if not story["scenes"]:
            cls.fail(
                "Story has no scene to use as its first scene."
            )

        return

    if first_scene_id not in scene_ids:
        cls.fail(
            f"first_scene_id references unknown scene: "
            f"{first_scene_id}"
        )

# ============================================================
# SCENE REFERENCES
# ============================================================

@classmethod
def _validate_scene_references(
    cls,
    scenes: dict[str, dict[str, Any]],
    role_ids: set[str],
    scene_ids: set[str],
) -> None:

    global_choice_ids: set[str] = set()

    for scene_id, scene in scenes.items():

        path = f"scene[{scene_id}]"

        for role_id in scene.get(
            "eligible_roles",
            [],
        ):
            if role_id not in role_ids:
                cls.fail(
                    f"{path}.eligible_roles references "
                    f"unknown role: {role_id}"
                )

        choices = scene.get(
            "choices",
            [],
        )

        for choice_index, choice in enumerate(choices):

            choice_path = (
                f"{path}.choices[{choice_index}]"
            )

            if not isinstance(
                choice,
                dict,
            ):
                cls.fail(
                    f"{choice_path} must be an object."
                )

            choice_id = choice.get("id")

            cls._require_id(
                choice_id,
                f"{choice_path}.id",
            )

            if choice_id in global_choice_ids:
                cls.fail(
                    f"Duplicate choice id across story: "
                    f"{choice_id}"
                )

            global_choice_ids.add(choice_id)

            label = choice.get("label")

            if not isinstance(
                label,
                str,
            ) or not label.strip():
                cls.fail(
                    f"{choice_path}.label must be a "
                    "non-empty string."
                )

            public_event = choice.get(
                "public_event",
                "",
            )

            if not isinstance(
                public_event,
                str,
            ):
                cls.fail(
                    f"{choice_path}.public_event must be a string."
                )

            next_scene = choice.get(
                "next_scene"
            )

            if next_scene is not None:
                cls._require_id(
                    next_scene,
                    f"{choice_path}.next_scene",
                )

                if next_scene not in scene_ids:
                    cls.fail(
                        f"{choice_path}.next_scene references "
                        f"unknown scene: {next_scene}"
                    )

            effects = choice.get(
                "effects",
                {},
            )

            cls._validate_effects(
                effects,
                role_ids,
                choice_path,
            )

            variants = choice.get(
                "public_event_variants"
            )

            if variants is not None:
                if not isinstance(
                    variants,
                    list,
                ) or not variants:
                    cls.fail(
                        f"{choice_path}.public_event_variants "
                        "must be a non-empty list."
                    )

                for variant_index, variant in enumerate(
                    variants
                ):
                    if not isinstance(
                        variant,
                        str,
                    ) or not variant.strip():
                        cls.fail(
                            f"{choice_path}.public_event_variants"
                            f"[{variant_index}] must be a "
                            "non-empty string."
                        )

            conditions = choice.get(
                "conditions",
                [],
            )

            cls._validate_conditions(
                conditions,
                role_ids,
                choice_path,
            )

            branch_priority = choice.get(
                "branch_priority",
                0,
            )

            if not isinstance(
                branch_priority,
                int,
            ) or isinstance(
                branch_priority,
                bool,
            ):
                cls.fail(
                    f"{choice_path}.branch_priority must be an integer."
                )

        transitions = scene.get(
            "transitions",
            [],
        )

        for transition_index, transition in enumerate(
            transitions
        ):

            transition_path = (
                f"{path}.transitions[{transition_index}]"
            )

            if not isinstance(
                transition,
                dict,
            ):
                cls.fail(
                    f"{transition_path} must be an object."
                )

            next_scene = transition.get(
                "next_scene"
            )

            cls._require_id(
                next_scene,
                f"{transition_path}.next_scene",
            )

            if next_scene not in scene_ids:
                cls.fail(
                    f"{transition_path}.next_scene references "
                    f"unknown scene: {next_scene}"
                )

            cls._validate_conditions(
                transition.get(
                    "conditions",
                    [],
                ),
                role_ids,
                transition_path,
            )

        late_join = scene.get(
            "late_join",
            {},
        )

        allowed_roles = late_join.get(
            "roles",
            [],
        )

        if not isinstance(
            allowed_roles,
            list,
        ):
            cls.fail(
                f"{path}.late_join.roles must be a list."
            )

        for role_id in allowed_roles:
            cls._require_id(
                role_id,
                f"{path}.late_join.roles",
            )

            if role_id not in role_ids:
                cls.fail(
                    f"{path}.late_join.roles references "
                    f"unknown role: {role_id}"
                )

        entry_scene = late_join.get(
            "entry_scene"
        )

        if entry_scene is not None:
            cls._require_id(
                entry_scene,
                f"{path}.late_join.entry_scene",
            )

            if entry_scene not in scene_ids:
                cls.fail(
                    f"{path}.late_join.entry_scene references "
                    f"unknown scene: {entry_scene}"
                )

        cls._validate_conditions(
            late_join.get(
                "conditions",
                [],
            ),
            role_ids,
            f"{path}.late_join",
        )

# ============================================================
# CONDITIONS
# ============================================================

@classmethod
def _validate_conditions(
    cls,
    conditions: Any,
    role_ids: set[str],
    path: str,
) -> None:

    if conditions is None:
        return

    if not isinstance(
        conditions,
        list,
    ):
        cls.fail(
            f"{path}.conditions must be a list."
        )

    for index, condition in enumerate(
        conditions
    ):

        condition_path = (
            f"{path}.conditions[{index}]"
        )

        if not isinstance(
            condition,
            dict,
        ):
            cls.fail(
                f"{condition_path} must be an object."
            )

        condition_type = condition.get(
            "type"
        )

        if condition_type not in cls.ALLOWED_CONDITION_TYPES:
            cls.fail(
                f"{condition_path}.type has unsupported value: "
                f"{condition_type}"
            )

        if condition_type == "flag":

            cls._require_name(
                condition.get("name"),
                f"{condition_path}.name",
            )

            if "value" in condition:
                cls._validate_json_value(
                    condition["value"],
                    f"{condition_path}.value",
                )

        elif condition_type == "variable":

            cls._require_name(
                condition.get("name"),
                f"{condition_path}.name",
            )

            operator = condition.get(
                "operator",
                "eq",
            )

            if operator not in cls.ALLOWED_OPERATORS:
                cls.fail(
                    f"{condition_path}.operator is unsupported: "
                    f"{operator}"
                )

            if "value" not in condition:
                cls.fail(
                    f"{condition_path}.value is required."
                )

            cls._validate_json_value(
                condition["value"],
                f"{condition_path}.value",
            )

        elif condition_type == "knowledge":

            role_id = condition.get(
                "role_id"
            )

            cls._require_id(
                role_id,
                f"{condition_path}.role_id",
            )

            if role_id not in role_ids:
                cls.fail(
                    f"{condition_path}.role_id references "
                    f"unknown role: {role_id}"
                )

            cls._require_name(
                condition.get("knowledge"),
                f"{condition_path}.knowledge",
            )

            if "value" in condition:
                if not isinstance(
                    condition["value"],
                    bool,
                ):
                    cls.fail(
                        f"{condition_path}.value must be boolean."
                    )

        elif condition_type == "relationship":

            role_a = condition.get(
                "role_a"
            )

            role_b = condition.get(
                "role_b"
            )

            cls._require_id(
                role_a,
                f"{condition_path}.role_a",
            )

            cls._require_id(
                role_b,
                f"{condition_path}.role_b",
            )

            if role_a == role_b:
                cls.fail(
                    f"{condition_path} cannot reference "
                    "the same role twice."
                )

            if role_a not in role_ids:
                cls.fail(
                    f"{condition_path}.role_a references "
                    f"unknown role: {role_a}"
                )

            if role_b not in role_ids:
                cls.fail(
                    f"{condition_path}.role_b references "
                    f"unknown role: {role_b}"
                )

            operator = condition.get(
                "operator",
                "eq",
            )

            if operator not in cls.ALLOWED_OPERATORS:
                cls.fail(
                    f"{condition_path}.operator is unsupported: "
                    f"{operator}"
                )

            expected = condition.get(
                "value",
                0,
            )

            if not isinstance(
                expected,
                (int, float),
            ) or isinstance(
                expected,
                bool,
            ):
                cls.fail(
                    f"{condition_path}.value must be numeric."
                )

# ============================================================
# EFFECTS
# ============================================================

@classmethod
def _validate_effects(
    cls,
    effects: Any,
    role_ids: set[str],
    path: str,
) -> None:

    if effects is None:
        cls.fail(
            f"{path}.effects cannot be null."
        )

    if not isinstance(
        effects,
        dict,
    ):
        cls.fail(
            f"{path}.effects must be an object."
        )

    unknown_keys = set(effects) - cls.ALLOWED_EFFECT_KEYS

    if unknown_keys:
        cls.fail(
            f"{path}.effects contains unsupported keys: "
            + ", ".join(sorted(unknown_keys))
        )

    set_flags = effects.get(
        "set_flags"
    )

    if set_flags is not None:
        if not isinstance(
            set_flags,
            dict,
        ):
            cls.fail(
                f"{path}.effects.set_flags must be an object."
            )

        for name, value in set_flags.items():
            cls._require_name(
                name,
                f"{path}.effects.set_flags key",
            )
            cls._validate_json_value(
                value,
                f"{path}.effects.set_flags[{name}]",
            )

    remove_flags = effects.get(
        "remove_flags"
    )

    if remove_flags is not None:
        if not isinstance(
            remove_flags,
            list,
        ):
            cls.fail(
                f"{path}.effects.remove_flags must be a list."
            )

        for index, name in enumerate(
            remove_flags
        ):
            cls._require_name(
                name,
                f"{path}.effects.remove_flags[{index}]",
            )

    set_variables = effects.get(
        "set_variables"
    )

    if set_variables is not None:
        if not isinstance(
            set_variables,
            dict,
        ):
            cls.fail(
                f"{path}.effects.set_variables must be an object."
            )

        for name, value in set_variables.items():
            cls._require_name(
                name,
                f"{path}.effects.set_variables key",
            )
            cls._validate_json_value(
                value,
                f"{path}.effects.set_variables[{name}]",
            )

    add_variables = effects.get(
        "add_variables"
    )

    if add_variables is not None:
        if not isinstance(
            add_variables,
            dict,
        ):
            cls.fail(
                f"{path}.effects.add_variables must be an object."
            )

        for name, amount in add_variables.items():
            cls._require_name(
                name,
                f"{path}.effects.add_variables key",
            )

            if not isinstance(
                amount,
                (int, float),
            ) or isinstance(
                amount,
                bool,
            ):
                cls.fail(
                    f"{path}.effects.add_variables[{name}] "
                    "must be numeric."
                )

    relationships = effects.get(
        "relationships"
    )

    if relationships is not None:
        if not isinstance(
            relationships,
            list,
        ):
            cls.fail(
                f"{path}.effects.relationships must be a list."
            )

        for index, relationship in enumerate(
            relationships
        ):

            relationship_path = (
                f"{path}.effects.relationships[{index}]"
            )

            if not isinstance(
                relationship,
                dict,
            ):
                cls.fail(
                    f"{relationship_path} must be an object."
                )

            role_a = relationship.get(
                "role_a"
            )

            role_b = relationship.get(
                "role_b"
            )

            cls._require_id(
                role_a,
                f"{relationship_path}.role_a",
            )

            cls._require_id(
                role_b,
                f"{relationship_path}.role_b",
            )

            if role_a == role_b:
                cls.fail(
                    f"{relationship_path} cannot target "
                    "the same role twice."
                )

            if role_a not in role_ids:
                cls.fail(
                    f"{relationship_path}.role_a references "
                    f"unknown role: {role_a}"
                )

            if role_b not in role_ids:
                cls.fail(
                    f"{relationship_path}.role_b references "
                    f"unknown role: {role_b}"
                )

            amount = relationship.get(
                "amount",
                0,
            )

            if not isinstance(
                amount,
                (int, float),
            ) or isinstance(
                amount,
                bool,
            ):
                cls.fail(
                    f"{relationship_path}.amount must be numeric."
                )

    knowledge = effects.get(
        "knowledge"
    )

    if knowledge is not None:
        if not isinstance(
            knowledge,
            list,
        ):
            cls.fail(
                f"{path}.effects.knowledge must be a list."
            )

        for index, item in enumerate(
            knowledge
        ):

            item_path = (
                f"{path}.effects.knowledge[{index}]"
            )

            if not isinstance(
                item,
                dict,
            ):
                cls.fail(
                    f"{item_path} must be an object."
                )

            role_id = item.get(
                "role_id"
            )

            cls._require_id(
                role_id,
                f"{item_path}.role_id",
            )

            if role_id not in role_ids:
                cls.fail(
                    f"{item_path}.role_id references "
                    f"unknown role: {role_id}"
                )

            cls._require_name(
                item.get("knowledge"),
                f"{item_path}.knowledge",
            )

            value = item.get(
                "value",
                True,
            )

            if not isinstance(
                value,
                bool,
            ):
                cls.fail(
                    f"{item_path}.value must be boolean."
                )

    secrets = effects.get(
        "secrets"
    )

    if secrets is not None:
        if not isinstance(
            secrets,
            list,
        ):
            cls.fail(
                f"{path}.effects.secrets must be a list."
            )

        seen_secret_ids: set[str] = set()

        for index, item in enumerate(
            secrets
        ):

            item_path = (
                f"{path}.effects.secrets[{index}]"
            )

            if not isinstance(
                item,
                dict,
            ):
                cls.fail(
                    f"{item_path} must be an object."
                )

            secret_id = item.get(
                "id"
            )

            cls._require_id(
                secret_id,
                f"{item_path}.id",
            )

            if secret_id in seen_secret_ids:
                cls.fail(
                    f"Duplicate secret id within effects: "
                    f"{secret_id}"
                )

            seen_secret_ids.add(
                secret_id
            )

            owner = item.get(
                "owner"
            )

            if owner is not None:
                cls._require_id(
                    owner,
                    f"{item_path}.owner",
                )

                if owner not in role_ids:
                    cls.fail(
                        f"{item_path}.owner references "
                        f"unknown role: {owner}"
                    )

            revealed = item.get(
                "revealed",
                False,
            )

            if not isinstance(
                revealed,
                bool,
            ):
                cls.fail(
                    f"{item_path}.revealed must be boolean."
                )

            revealed_to = item.get(
                "revealed_to",
                [],
            )

            if not isinstance(
                revealed_to,
                list,
            ):
                cls.fail(
                    f"{item_path}.revealed_to must be a list."
                )

            for role_id in revealed_to:
                cls._require_id(
                    role_id,
                    f"{item_path}.revealed_to",
                )

                if role_id not in role_ids:
                    cls.fail(
                        f"{item_path}.revealed_to references "
                        f"unknown role: {role_id}"
                    )

    character_state = effects.get(
        "character_state"
    )

    if character_state is not None:
        if not isinstance(
            character_state,
            dict,
        ):
            cls.fail(
                f"{path}.effects.character_state must be an object."
            )

        # Character state is intentionally data-only.
        # No executable values are permitted.
        cls._validate_json_value(
            character_state,
            f"{path}.effects.character_state",
        )

    for text_key in (
        "text",
        "description",
    ):
        if text_key in effects:
            value = effects[text_key]

            if not isinstance(
                value,
                str,
            ):
                cls.fail(
                    f"{path}.effects.{text_key} must be a string."
                )

# ============================================================
# ENDINGS
# ============================================================

@classmethod
def _validate_ending(
    cls,
    ending: Any,
    path: str,
) -> None:

    ending_path = f"{path}.ending"

    if isinstance(
        ending,
        str,
    ):
        if not ending.strip():
            cls.fail(
                f"{ending_path} cannot be empty."
            )
        return

    if not isinstance(
        ending,
        dict,
    ):
        cls.fail(
            f"{ending_path} must be a string or object."
        )

    ending_id = ending.get(
        "id"
    )

    cls._require_id(
        ending_id,
        f"{ending_path}.id",
    )

    text = ending.get(
        "text"
    )

    if not isinstance(
        text,
        str,
    ) or not text.strip():
        cls.fail(
            f"{ending_path}.text must be a non-empty string."
        )

    conditions = ending.get(
        "conditions",
        [],
    )

    if not isinstance(
        conditions,
        list,
    ):
        cls.fail(
            f"{ending_path}.conditions must be a list."
        )

# ============================================================
# CROSS REFERENCES
# ============================================================

@classmethod
def _validate_cross_references(
    cls,
    story: dict[str, Any],
    roles: dict[str, dict[str, Any]],
    scenes: dict[str, dict[str, Any]],
) -> None:

    role_ids = set(roles)
    scene_ids = set(scenes)

    # Every playable role must be usable somewhere in the story.
    playable_roles = {
        role_id
        for role_id, role in roles.items()
        if role.get("playable", True)
    }

    referenced_roles: set[str] = set()

    for scene in scenes.values():

        referenced_roles.update(
            scene.get(
                "eligible_roles",
                [],
            )
        )

        referenced_roles.update(
            scene.get(
                "late_join",
                {},
            ).get(
                "roles",
                [],
            )
        )

        for choice in scene.get(
            "choices",
            [],
        ):
            cls._collect_roles_from_conditions(
                choice.get(
                    "conditions",
                    [],
                ),
                referenced_roles,
            )

            cls._collect_roles_from_effects(
                choice.get(
                    "effects",
                    {},
                ),
                referenced_roles,
            )

        for transition in scene.get(
            "transitions",
            [],
        ):
            cls._collect_roles_from_conditions(
                transition.get(
                    "conditions",
                    [],
                ),
                referenced_roles,
            )

        cls._collect_roles_from_conditions(
            scene.get(
                "late_join",
                {},
            ).get(
                "conditions",
                [],
            ),
            referenced_roles,
        )

        ending = scene.get(
            "ending"
        )

        if isinstance(
            ending,
            dict,
        ):
            cls._collect_roles_from_conditions(
                ending.get(
                    "conditions",
                    [],
                ),
                referenced_roles,
            )

    unknown_referenced_roles = (
        referenced_roles - role_ids
    )

    if unknown_referenced_roles:
        cls.fail(
            "Story contains unknown role references: "
            + ", ".join(
                sorted(unknown_referenced_roles)
            )
        )

    # A playable role that is never available is almost certainly
    # a generation error and should not consume a player slot.
    unused_playable = (
        playable_roles - referenced_roles
    )

    if unused_playable and len(playable_roles) > 1:
        cls.fail(
            "Playable roles are never referenced by the story: "
            + ", ".join(sorted(unused_playable))
        )

    # Every ending must have a meaningful id when represented as
    # an object, and every scene must have either a direct ending
    # or a path toward one. Graph validation below handles paths.
    ending_scenes = [
        scene_id
        for scene_id, scene in scenes.items()
        if scene.get("ending") is not None
    ]

    if not ending_scenes:
        cls.fail(
            "Story must contain at least one ending scene."
        )

@classmethod
def _collect_roles_from_conditions(
    cls,
    conditions: Any,
    output: set[str],
) -> None:

    if not isinstance(
        conditions,
        list,
    ):
        return

    for condition in conditions:

        if not isinstance(
            condition,
            dict,
        ):
            continue

        condition_type = condition.get(
            "type"
        )

        if condition_type == "knowledge":
            role_id = condition.get(
                "role_id"
            )

            if isinstance(
                role_id,
                str,
            ):
                output.add(role_id)

        elif condition_type == "relationship":

            for key in (
                "role_a",
                "role_b",
            ):
                role_id = condition.get(
                    key
                )

                if isinstance(
                    role_id,
                    str,
                ):
                    output.add(role_id)

@classmethod
def _collect_roles_from_effects(
    cls,
    effects: Any,
    output: set[str],
) -> None:

    if not isinstance(
        effects,
        dict,
    ):
        return

    for relationship in effects.get(
        "relationships",
        [],
    ):
        if not isinstance(
            relationship,
            dict,
        ):
            continue

        for key in (
            "role_a",
            "role_b",
        ):
            role_id = relationship.get(
                key
            )

            if isinstance(
                role_id,
                str,
            ):
                output.add(role_id)

    for item in effects.get(
        "knowledge",
        [],
    ):
        if not isinstance(
            item,
            dict,
        ):
            continue

        role_id = item.get(
            "role_id"
        )

        if isinstance(
            role_id,
            str,
        ):
            output.add(role_id)

    for item in effects.get(
        "secrets",
        [],
    ):
        if not isinstance(
            item,
            dict,
        ):
            continue

        owner = item.get(
            "owner"
        )

        if isinstance(
            owner,
            str,
        ):
            output.add(owner)

        revealed_to = item.get(
            "revealed_to",
            [],
        )

        if isinstance(
            revealed_to,
            list,
        ):
            output.update(
                role_id
                for role_id in revealed_to
                if isinstance(
                    role_id,
                    str,
                )
            )

# ============================================================
# GRAPH VALIDATION
# ============================================================

@classmethod
def _validate_story_graph(
    cls,
    story: dict[str, Any],
    scenes: dict[str, dict[str, Any]],
) -> None:

    scene_ids = set(scenes)

    first_scene_id = story.get(
        "first_scene_id"
    )

    if first_scene_id is None:
        first_scene_id = story["scenes"][0]["id"]

    if first_scene_id not in scene_ids:
        cls.fail(
            f"First scene does not exist: {first_scene_id}"
        )

    ending_scenes = {
        scene_id
        for scene_id, scene in scenes.items()
        if scene.get("ending") is not None
    }

    if not ending_scenes:
        cls.fail(
            "Story has no ending scenes."
        )

    graph: dict[str, set[str]] = defaultdict(set)

    for scene_id, scene in scenes.items():

        for choice in scene.get(
            "choices",
            [],
        ):
            target = choice.get(
                "next_scene"
            )

            if target is not None:
                graph[scene_id].add(
                    target
                )

        for transition in scene.get(
            "transitions",
            [],
        ):
            target = transition.get(
                "next_scene"
            )

            if target is not None:
                graph[scene_id].add(
                    target
                )

        entry_scene = scene.get(
            "late_join",
            {},
        ).get(
            "entry_scene"
        )

        if entry_scene is not None:
            graph[scene_id].add(
                entry_scene
            )

    # --------------------------------------------------------
    # Reachability from first scene
    # --------------------------------------------------------

    reachable: set[str] = set()
    stack = [first_scene_id]

    while stack:

        current = stack.pop()

        if current in reachable:
            continue

        reachable.add(current)

        stack.extend(
            graph.get(
                current,
                set(),
            )
            - reachable
        )

    unreachable = scene_ids - reachable

    if unreachable:
        cls.fail(
            "Story contains unreachable scenes: "
            + ", ".join(sorted(unreachable))
        )

    # --------------------------------------------------------
    # Every reachable scene must be able to eventually reach
    # an ending.
    #
    # This prevents Gemini from creating a branch that traps
    # the game forever.
    # --------------------------------------------------------

    reverse_graph: dict[str, set[str]] = defaultdict(set)

    for source, targets in graph.items():
        for target in targets:
            reverse_graph[target].add(
                source
            )

    can_reach_ending = set(
        ending_scenes
    )

    stack = list(
        ending_scenes
    )

    while stack:

        current = stack.pop()

        for previous in reverse_graph.get(
            current,
            set(),
        ):
            if previous not in can_reach_ending:
                can_reach_ending.add(
                    previous
                )
                stack.append(
                    previous
                )

    dead_scenes = (
        reachable - can_reach_ending
    )

    if dead_scenes:
        cls.fail(
            "Story contains reachable scenes that cannot "
            "eventually reach an ending: "
            + ", ".join(sorted(dead_scenes))
        )

    # --------------------------------------------------------
    # Ending scenes should actually terminate the game.
    #
    # Choices may exist for display/final interaction, but no
    # outgoing next_scene is allowed from an ending scene.
    # --------------------------------------------------------

    for scene_id in ending_scenes:

        outgoing = graph.get(
            scene_id,
            set(),
        )

        if outgoing:
            cls.fail(
                f"Ending scene {scene_id} has outgoing scene "
                f"references: {sorted(outgoing)}"
            )

# ============================================================
# PLAYER COUNT
# ============================================================

@classmethod
def _validate_player_count(
    cls,
    roles: dict[str, dict[str, Any]],
    player_count: int | None,
) -> None:

    if player_count is None:
        return

    if not isinstance(
        player_count,
        int,
    ) or isinstance(
        player_count,
        bool,
    ):
        cls.fail(
            "player_count must be an integer."
        )

    if player_count < 1:
        cls.fail(
            "player_count must be at least 1."
        )

    playable_roles = [
        role_id
        for role_id, role in roles.items()
        if role.get(
            "playable",
            True,
        )
    ]

    if player_count > len(playable_roles):
        cls.fail(
            f"Story supports only {len(playable_roles)} playable roles "
            f"but requires {player_count} players."
        )

# ============================================================
# BASIC VALUE VALIDATION
# ============================================================

@classmethod
def _require_id(
    cls,
    value: Any,
    path: str,
) -> None:

    if not isinstance(
        value,
        str,
    ):
        cls.fail(
            f"{path} must be a string."
        )

    value = value.strip()

    if not value:
        cls.fail(
            f"{path} cannot be empty."
        )

    if len(value) > 100:
        cls.fail(
            f"{path} is too long."
        )

@classmethod
def _require_name(
    cls,
    value: Any,
    path: str,
) -> None:

    if not isinstance(
        value,
        str,
    ):
        cls.fail(
            f"{path} must be a string."
        )

    if not value.strip():
        cls.fail(
            f"{path} cannot be empty."
        )

    if len(value) > 200:
        cls.fail(
            f"{path} is too long."
        )

@classmethod
def _validate_json_value(
    cls,
    value: Any,
    path: str,
) -> None:
    """
    Ensure the generated value is JSON-compatible data.

    This intentionally rejects Python-specific values and other
    non-serializable objects before the story reaches Supabase.
    """

    if value is None:
        return

    if isinstance(
        value,
        (str, int, float, bool),
    ):
        return

    if isinstance(
        value,
        list,
    ):
        for index, item in enumerate(value):
            cls._validate_json_value(
                item,
                f"{path}[{index}]",
            )
        return

    if isinstance(
        value,
        dict,
    ):
        for key, item in value.items():

            if not isinstance(
                key,
                str,
            ):
                cls.fail(
                    f"{path} contains a non-string object key."
                )

            cls._validate_json_value(
                item,
                f"{path}.{key}",
            )

        return

    cls.fail(
        f"{path} contains unsupported JSON data: "
        f"{type(value).__name__}"
    )

# ============================================================
# FINGERPRINT
# ============================================================

@classmethod
def structural_fingerprint(
    cls,
    story: dict[str, Any],
) -> str:
    """
    Return a deterministic fingerprint of the story structure.

    Cosmetic text is intentionally excluded where possible.

    The fingerprint is suitable for the database-level unique
    constraint used by story_history.
    """

    validated = cls.validate(
        story
    )

    structural_roles = []

    for role in validated.get(
        "roles",
        [],
    ):
        structural_roles.append(
            {
                "id": role.get("id"),
                "playable": role.get(
                    "playable",
                    True,
                ),
            }
        )

    structural_scenes = []

    for scene in validated.get(
        "scenes",
        [],
    ):

        structural_choices = []

        for choice in scene.get(
            "choices",
            [],
        ):
            structural_choices.append(
                {
                    "id": choice.get("id"),
                    "next_scene": choice.get(
                        "next_scene"
                    ),
                    "branch_priority": choice.get(
                        "branch_priority",
                        0,
                    ),
                    "conditions": cls._canonical_json(
                        choice.get(
                            "conditions",
                            [],
                        )
                    ),
                    "effects": cls._structural_effects(
                        choice.get(
                            "effects",
                            {},
                        )
                    ),
                }
            )

        structural_scenes.append(
            {
                "id": scene.get("id"),
                "timer_seconds": scene.get(
                    "timer_seconds"
                ),
                "eligible_roles": sorted(
                    scene.get(
                        "eligible_roles",
                        [],
                    )
                ),
                "choices": structural_choices,
                "transitions": [
                    {
                        "next_scene": transition.get(
                            "next_scene"
                        ),
                        "conditions": cls._canonical_json(
                            transition.get(
                                "conditions",
                                [],
                            )
                        ),
                    }
                    for transition in scene.get(
                        "transitions",
                        [],
                    )
                ],
                "ending": cls._structural_ending(
                    scene.get(
                        "ending"
                    )
                ),
            }
        )

    structural = {
        "first_scene_id": validated.get(
            "first_scene_id"
        ) or validated["scenes"][0]["id"],
        "roles": structural_roles,
        "scenes": structural_scenes,
    }

    serialized = json.dumps(
        structural,
        sort_keys=True,
        separators=(
            ",",
            ":",
            ),
        ensure_ascii=False,
    )

    return hashlib.sha256(
        serialized.encode(
            "utf-8"
        )
    ).hexdigest()

@classmethod
def _structural_effects(
    cls,
    effects: Any,
) -> Any:

    if not isinstance(
        effects,
        dict,
    ):
        return effects

    cosmetic = {
        "text",
        "description",
    }

    return {
        key: cls._canonical_json(value)
        for key, value in effects.items()
        if key not in cosmetic
    }

@classmethod
def _structural_ending(
    cls,
    ending: Any,
) -> Any:

    if isinstance(
        ending,
        str,
    ):
        return {
            "type": "text"
        }

    if isinstance(
        ending,
        dict,
    ):
        return {
            "id": ending.get(
                "id"
            ),
            "conditions": cls._canonical_json(
                ending.get(
                    "conditions",
                    [],
                )
            ),
        }

    return None

@staticmethod
def _canonical_json(
    value: Any,
) -> Any:
    """
    Produce deterministic JSON-compatible data without changing
    the semantic value.
    """

    if isinstance(
        value,
        dict,
    ):
        return {
            key: StoryValidator._canonical_json(
                value[key]
            )
            for key in sorted(
                value.keys()
            )
        }

    if isinstance(
        value,
        list,
    ):
        return [
            StoryValidator._canonical_json(
                item
            )
            for item in value
        ]

    return value

# ============================================================
# ERROR HELPER
# ============================================================

@staticmethod
def fail(
    message: str,
) -> None:
    raise StoryValidationError(
        message
    )
